export const levelsData = [
  {
    name: 'الحزام الأبيض',
    nameEn: 'White Belt',
    rankOrder: 1,
    iconEmoji: '⚪',
    description: 'بناء الثقة — الأساسيات والعمليات البسيطة',
    descriptionEn: 'Confidence Builder — basics and simple operations',
  },
  {
    name: 'الحزام الأصفر',
    nameEn: 'Yellow Belt',
    rankOrder: 2,
    iconEmoji: '🟡',
    description: 'بناء المهارات — الكسور والأعداد العشرية والأنماط',
    descriptionEn: 'Building Skills — fractions, decimals, and patterns',
  },
  {
    name: 'الحزام البرتقالي',
    nameEn: 'Orange Belt',
    rankOrder: 3,
    iconEmoji: '🟠',
    description: 'الإتقان — عمليات الكسور والعشرية المتقدمة',
    descriptionEn: 'Mastery — advanced fractions and decimal operations',
  },
  {
    name: 'الحزام الأخضر',
    nameEn: 'Green Belt',
    rankOrder: 4,
    iconEmoji: '🟢',
    description: 'الخبير — النسب والجبر والسرعة',
    descriptionEn: 'Expert — ratios, algebra, and speed',
  },
  {
    name: 'الحزام الأسود',
    nameEn: 'Black Belt',
    rankOrder: 5,
    iconEmoji: '🥋',
    description: 'النينجا الأعلى — الأسس والاحتمالات والألغاز',
    descriptionEn: 'Supreme Ninja — exponents, probability, and puzzles',
  },
];

export const topicsPerLevel: Record<number, { name: string; nameEn: string; description: string; descriptionEn: string }[]> = {
  1: [
    { name: 'الجمع والطرح', nameEn: 'Addition & Subtraction', description: 'جمع وطرح أعداد كبيرة', descriptionEn: 'Multi-digit addition and subtraction' },
    { name: 'الضرب', nameEn: 'Multiplication', description: 'ضرب أعداد من رقمين وثلاثة', descriptionEn: '2-3 digit multiplication' },
    { name: 'القسمة والباقي', nameEn: 'Division with Remainders', description: 'قسمة مع باقي وبدون', descriptionEn: 'Division with and without remainders' },
    { name: 'حس الأعداد', nameEn: 'Number Sense', description: 'القيمة المكانية والتقريب والمقارنة', descriptionEn: 'Place value, rounding, comparing' },
    { name: 'خصائص الأعداد', nameEn: 'Number Properties', description: 'زوجي/فردي، العوامل، المضاعفات', descriptionEn: 'Even/odd, factors, multiples' },
    { name: 'مقدمة الكسور', nameEn: 'Intro to Fractions', description: 'قراءة ومقارنة الكسور المتكافئة', descriptionEn: 'Reading and comparing fractions' },
    { name: 'القياس والوحدات', nameEn: 'Measurement', description: 'الطول والوزن والسعة', descriptionEn: 'Length, weight, and capacity' },
  ],
  2: [
    { name: 'جمع وطرح الكسور', nameEn: 'Add/Subtract Fractions', description: 'كسور بنفس المقام', descriptionEn: 'Same denominator fractions' },
    { name: 'الأعداد العشرية', nameEn: 'Decimals', description: 'قراءة ومقارنة وترتيب', descriptionEn: 'Reading, comparing, ordering' },
    { name: 'جمع وطرح العشرية', nameEn: 'Add/Subtract Decimals', description: 'عمليات على الأعداد العشرية', descriptionEn: 'Decimal addition and subtraction' },
    { name: 'الوقت والمواعيد', nameEn: 'Time Calculations', description: 'حساب الوقت والمدة', descriptionEn: 'Duration and time problems' },
    { name: 'المحيط والمساحة', nameEn: 'Perimeter & Area', description: 'محيط ومساحة المستطيل والمربع', descriptionEn: 'Rectangles and squares' },
    { name: 'التقدير والتقريب', nameEn: 'Estimation', description: 'تقدير النتائج والتقريب', descriptionEn: 'Rounding and approximation' },
    { name: 'الأنماط والتسلسلات', nameEn: 'Patterns & Sequences', description: 'إيجاد النمط وإكمال التسلسل', descriptionEn: 'Find the pattern, what comes next' },
  ],
  3: [
    { name: 'الكسور المختلفة المقامات', nameEn: 'Unlike Fractions', description: 'جمع وطرح كسور مختلفة المقام', descriptionEn: 'Different denominator fractions' },
    { name: 'ضرب الكسور', nameEn: 'Multiplying Fractions', description: 'ضرب كسور في أعداد صحيحة وكسور', descriptionEn: 'Fraction times whole number or fraction' },
    { name: 'قسمة الكسور', nameEn: 'Dividing Fractions', description: 'قسمة كسور على أعداد صحيحة وكسور', descriptionEn: 'Fraction divided by whole number' },
    { name: 'الأعداد الكسرية', nameEn: 'Mixed Numbers', description: 'الأعداد الكسرية والكسور غير الفعلية', descriptionEn: 'Mixed and improper fractions' },
    { name: 'ضرب وقسمة العشرية', nameEn: 'Multiply/Divide Decimals', description: 'ضرب وقسمة الأعداد العشرية', descriptionEn: 'Decimal multiplication and division' },
    { name: 'ترتيب العمليات', nameEn: 'Order of Operations', description: 'الأقواس والضرب قبل الجمع', descriptionEn: 'BODMAS — brackets first' },
    { name: 'المال والأعمال', nameEn: 'Money Math', description: 'الربح والخسارة والميزانية', descriptionEn: 'Profit, loss, and budgets' },
  ],
  4: [
    { name: 'النسبة والتناسب', nameEn: 'Ratio & Proportion', description: 'النسبة بين كميتين والتناسب', descriptionEn: 'Ratios and proportional reasoning' },
    { name: 'النسبة المئوية', nameEn: 'Percentages', description: 'حساب النسبة المئوية لعدد', descriptionEn: 'Finding percentages of numbers' },
    { name: 'تطبيقات النسبة المئوية', nameEn: '% Applications', description: 'الخصم والزيادة والنقصان', descriptionEn: 'Discounts, price changes' },
    { name: 'مقدمة الجبر', nameEn: 'Intro to Algebra', description: 'التعبيرات الجبرية والمتغيرات', descriptionEn: 'Variables and expressions' },
    { name: 'المعادلات البسيطة', nameEn: 'Simple Equations', description: 'حل معادلات من خطوة واحدة', descriptionEn: 'One-step equations' },
    { name: 'السرعة والمسافة والزمن', nameEn: 'Speed/Distance/Time', description: 'حساب السرعة والمسافة والوقت', descriptionEn: 'Speed, distance, and time' },
    { name: 'المتوسط الحسابي', nameEn: 'Averages', description: 'حساب المتوسط لمجموعة أعداد', descriptionEn: 'Mean of a set of numbers' },
  ],
  5: [
    { name: 'الأسس والقوى', nameEn: 'Powers & Exponents', description: 'الأس والتربيع والتكعيب', descriptionEn: 'Squares, cubes, and powers' },
    { name: 'العوامل المشتركة والمضاعفات', nameEn: 'GCD & LCM', description: 'ع.م.أ و م.م.أ', descriptionEn: 'Greatest common divisor and least common multiple' },
    { name: 'الأعداد السالبة', nameEn: 'Negative Numbers', description: 'مقدمة الأعداد السالبة وجمعها وطرحها', descriptionEn: 'Intro to negative numbers' },
    { name: 'الاحتمالات', nameEn: 'Probability', description: 'احتمال بسيط: نرد وعملة وكروت', descriptionEn: 'Simple probability: dice, coins' },
    { name: 'الحجم', nameEn: 'Volume', description: 'حجم المكعب ومتوازي المستطيلات', descriptionEn: 'Cubes and rectangular prisms' },
    { name: 'المعادلات المتقدمة', nameEn: '2-Step Equations', description: 'حل معادلات من خطوتين', descriptionEn: 'Two-step equations' },
    { name: 'ألغاز رياضية', nameEn: 'Math Puzzles', description: 'أكمل الرقم الناقص والمنطق', descriptionEn: 'Find the missing number, logic' },
  ],
};
